### ISSUE TITLE
Update ChebyKAN

### ISSUE THREAD

**Issue by iiisak** [lif314/X-KANeRF#2]
ChebyKAN has a faster vectorized implemention not using the recursive form you have in your implementation

**Comment by lif314** [comment]
> ChebyKAN has a faster vectorized implemention not using the recursive form you have in your implementation

Thank you very much. I have tested faster ChebyKAN. However, `NAN` appears during training, causing the model to fail to converge. There may be unknown bugs in faster ChebyKAN or my code.

**Comment by lif314** [comment]
> ChebyKAN has a faster vectorized implemention not using the recursive form you have in your implementation

Thanks again. The `NaN` error during training is probably due to numerical instability in `acos`. I mitigated this by ensuring `x` stays within `[-1, 1]` with a small margin. You can see my changes [here](https://github.com/lif314/X-KANeRF/blob/main/xKANeRF/xKAN/chebyshev_kan.py#L57C1-L57C9). Now faster ChebyKAN works fine in my experiments.

**Comment by iiisak** [comment]
Would you mind submitting this issue/change to the ChebyKAN repository?
